import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { IMAGE } from '@digest/docker';

// Minimal spawn surface so tests can inject a fake child process.
export type SpawnLike = (
  cmd: string, args: string[], opts: { stdio: 'inherit' },
) => {
  on(event: 'error', cb: (err: Error) => void): unknown;
  on(event: 'exit', cb: (code: number | null) => void): unknown;
};

// Locate the packaged docker/ build context (generated by the build from
// @digest/docker's dist/docker). Works from dist/ (published) and from
// src/ (dev via tsx) — package.json sits one level up in both layouts.
function dockerContext(): string {
  const here = dirname(fileURLToPath(import.meta.url));
  return join(here, '..', 'docker');
}

// Build the local image. The CloakBrowser binary licence permits internal/
// derived images but forbids redistribution, so this image is built on the
// user's machine and never pushed to any registry.
export async function setup(
  spawnFn: SpawnLike = spawn,
): Promise<number> {
  const context = dockerContext();
  console.log(`Building ${IMAGE} from ${context} ...`);
  console.log(
    'Note: this image embeds CloakBrowser and is for local use only — ' +
    'do not push it to any registry (binary licence forbids redistribution).',
  );
  return await new Promise((resolve) => {
    const child = spawnFn(
      'docker', ['build', '-t', IMAGE, context],
      { stdio: 'inherit' },
    );
    child.on('error', (err) => {
      console.error(
        `docker build could not start: ${err.message}\n` +
        'Is Docker installed and running?',
      );
      resolve(1);
    });
    child.on('exit', (code) => {
      if (code === 0) {
        console.log(`\nDone. ${IMAGE} built. Run \`digest doctor\` ` +
          'to verify, then restart Claude Code.');
      }
      resolve(code ?? 1);
    });
  });
}
